# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39bf6473a79e7580051ca5a90bdfc94bb38733627ebe162ac69451075949abfe27a069ea7832338c49e02e43119b4a9d215a7b71a813ca75fa5fc844d42391fd

test:
  secret_key_base: fb2ba7f810c546992b9f958a80b9b50bb538c9fe4e02fff161e9f33e1a07e4d17c2d1e1ab6b26ce6920e09921d08a7197522dca6bf11439231f261e8cdbafbc4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
